
[phases.setup]
nixPkgs = ['nodejs', 'yarn']

[phases.install]
cmds = ['yarn install']

[phases.buildfrontend]
cmds = ['yarn run frontend:build']
dependsOn = ['build']

[start]
cmd = 'yarn run start'
