
[phases.setup]
nixPkgs = ['nodejs', 'yarn']

[phases.install]
cmds = ['yarn install']

[phases.build]
cmds = ['yarn run build']

[phases.postbuild]
cmds = ['cd packages/backend/public && ls']
dependsOn = ['build']

[start]
cmd = 'cd packages/backend/public && ls && node packages/backend/index.js'
dependsOn = ['build']
