
[phases.setup]
nixPkgs = ['nodejs', 'yarn']

[phases.install]
cmds = ['yarn install']

[phases.build]
cmds = ['yarn run build']

[phases.postbuild]
cmds = ['cd packages/backend && ls']
dependsOn = ['build']

[start]
cmd = 'cd packages/backend && ls && yarn run start'
