
[phases.setup]
nixPkgs = ['nodejs', 'yarn']

[phases.install]
cmds = ['yarn install']

[phases.build]
cmds = ['yarn run build', 'cp packages/frontend/public packages/backend']

[start]
cmd = 'yarn run start'
